sudo: required
services:
- docker
before_install:
- docker build -t nvtuong/frontend -f Dockerfile.dev .
script:
- docker run -e CI=true nvtuong/frontend yarn test --coverage
deploy:
  provider: heroku
  api_key:
    secure: icLiVwrpcEFtx1Z4fxHD5kwkk5LR5y5RHVfFSd3R+r60WXGw6enLVKZpKWAUY7cxdbBC3xtv3pVirlHam2OZlZXCJ+4RezWzaeHSwnWcW0ab8I+tCY+v9YHPWKL+Rv29/xIdnyjzH2Thk6MWaWpNknOH5qbgSKvbYQhMrBIPjLgEtJ8RpXNH6yl2mRH/XviUXwEkjMiATciaiP/a1w0XHQvMix+9H3YvRE1fPQoiHxcGTKoRHXTuc1X5aYDRvAEoOItnuhrHHP1TGUkJSWauuSZYiErJ3reUiCFE0pKRdWLckOW4MROYdz2Kz4ft5zdU7qe5PXt/FIvze3bE3H8krlMsQROlCuOMhCrQzYQWzU6azOLwH1NtEPsp8xxsBvEik8LpC7vdn8STqcMsIfqxRL7OTMKixpjjjvvhj6qf4BsEusRCa68DfHRAIw2WTNKcj2Is7wo6m5I0rZdXlEyRxVBwVoiOyftdlLRFftPPzUgLatr/4wGc2udo8Tl2H0BQ7H/OE90RnQfMGWyNouaVgEaa5PkDXZqBZiZEbwNqOTbY7V9/rgGzup1NcnToKwvkXst6i2aIFxLMGj+JlWUjxz0inQZHRFZ1geyVIA30N4PGr9388mZkZ+6jt0Dres8IrBbeP5BnYU5DHTmr3Rl+T35yRnXpmjLa0qWzmtGmt/Q=
  on:
    branch: master
